// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTKPX_UiYN1ilqtzhbPh7SkGlQAD0B6kA',
    appId: '1:850518864427:web:9ca1b73f26228cd52ff06e',
    messagingSenderId: '850518864427',
    projectId: 'my-hive-d509e',
    authDomain: 'my-hive-d509e.firebaseapp.com',
    storageBucket: 'my-hive-d509e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGCLxZsBx9rqfj_QowKxeySFf6xLqBr0c',
    appId: '1:850518864427:android:ddffadf6d11577522ff06e',
    messagingSenderId: '850518864427',
    projectId: 'my-hive-d509e',
    storageBucket: 'my-hive-d509e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6_J6JlFV4zJLyHQfvw9t4-_nrEAseGVQ',
    appId: '1:850518864427:ios:e677d9391028ca4a2ff06e',
    messagingSenderId: '850518864427',
    projectId: 'my-hive-d509e',
    storageBucket: 'my-hive-d509e.firebasestorage.app',
    iosBundleId: 'com.example.myhive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6_J6JlFV4zJLyHQfvw9t4-_nrEAseGVQ',
    appId: '1:850518864427:ios:e677d9391028ca4a2ff06e',
    messagingSenderId: '850518864427',
    projectId: 'my-hive-d509e',
    storageBucket: 'my-hive-d509e.firebasestorage.app',
    iosBundleId: 'com.example.myhive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTKPX_UiYN1ilqtzhbPh7SkGlQAD0B6kA',
    appId: '1:850518864427:web:e3ef6d3e91e26c492ff06e',
    messagingSenderId: '850518864427',
    projectId: 'my-hive-d509e',
    authDomain: 'my-hive-d509e.firebaseapp.com',
    storageBucket: 'my-hive-d509e.firebasestorage.app',
  );
}
